- name: Install Rails
  hosts: apps
  sudo: yes
  tags:
    - provisioning
  vars_files:
    - group_vars/pubkeys.yml
  pre_tasks:
        # I've had problems with locale and postgresql, this might help
    - locale_gen: name=de_DE.UTF-8 state=present
    - locale_gen: name=en_US.UTF-8 state=present
  roles:
    - role: debops.users
      users_list:
        - "{{ app_user }}"
      - name: "{{ app_user }}"
        comment: "Application user"
        sshkeys:
        - "{{pubkeys.some_user}}"
    - role: ANXS.postgresql
      postgresql_databases:
        - name: '{{rails_database_name}}'
      postgresql_users:
        - name: '{{rails_database_user}}'
          role_attr_flags: CREATEDB,SUPERUSER
    - dresden-weekly.Rails/ruby/postgresql
    - dresden-weekly.Rails/ruby/rvm
        # imagemagick + rmagick dependencies + pngquant jpegoptim
    - dresden-weekly.Rails/rails/folders
    - role: dresden-weekly.Rails/user/profile
      rails_user_name: "{{ app_user }}"
      rails_user_bashrc_lines:
        - "cd {{ RAILS_APP_BASE_PATH }} || true"
        - "cd {{ RAILS_APP_CURRENT_PATH }} || true"
        # install nginx + configure app-site and enable it
    - dresden-weekly.Rails/nginx/passenger
        # simple daily crontab dump of pg database - sufficient for many app sizes
